"""Core-backed numeric and presentation facade for Galaga 2.

Top-level :mod:`galaga` re-exports this manifest with exact object identity.
This namespace owns numeric wrappers, expression tracking, and presentation.
"""

from types import MappingProxyType

from ..blades import (
    BladeConvention,
    BladeLabel,
    BladeRef,
    DisplayOrder,
    LocalNamePolicy,
    complex_blade_convention,
    default_blade_convention,
    euclidean_blade_convention,
    exterior_blade_convention,
    indexed_blade_convention,
    lengyel_cga_blade_convention,
    lengyel_cga_display_order,
    null_cga_blade_convention,
    orthogonal_cga_blade_convention,
    pga_blade_convention,
    quaternion_blade_convention,
    quaternion_display_order,
    rga_blade_convention,
    rga_display_order,
    spacetime_blade_convention,
)
from ..composition import ConfiguredPreset, NotationPatch, PresentationRecipe
from ..display import build_tree as build_render_tree
from ..display import render
from ..expression import (
    BladeLiteral,
    Call,
    Expr,
    Expression,
    MultivectorLiteral,
    ScalarLiteral,
    Symbol,
    evaluate,
    simplify,
)
from ..names import Name
from ..presentation import (
    AlgebraConfig,
    AlgebraDefinition,
    DisplayPolicy,
    ModelConfig,
    Notation,
    PresentationConfig,
    RenderRule,
    default_presentation,
)
from ..presenter import PresentedMultivector, Presenter
from ..presets import (
    CGAPreset,
    ComplexPreset,
    EuclideanPreset,
    ExteriorPreset,
    LengyelCGAPreset,
    LengyelRGAPreset,
    ObliquePlanePreset,
    PGAPreset,
    Preset,
    QuaternionPreset,
    SpacetimePreset,
)
from ._numeric import (
    Algebra,
    BasisMultivectors,
    LocalMultivectors,
    Multivector,
    add,
    anticommutator,
    antidot_product,
    antimetric_apply,
    antireverse,
    antiwedge,
    clifford_conjugate,
    commutator,
    complement,
    conjugate,
    divide,
    doran_lasenby_inner,
    dual,
    even_grades,
    exp,
    geometric_antiproduct,
    geometric_product,
    grade,
    grade_involution,
    grades,
    half_anticommutator,
    half_commutator,
    hestenes_inner,
    inverse,
    is_basis_blade,
    is_bivector,
    is_even,
    is_rotor,
    is_rotor_generator,
    is_scalar,
    is_vector,
    jordan_product,
    left_complement,
    left_contraction,
    left_hodge_dual,
    left_interior_product,
    left_weight_dual,
    lie_bracket,
    log,
    metric_apply,
    metric_inner_product,
    metric_regressive_product,
    negate,
    norm,
    norm2,
    odd_grades,
    outer_product,
    outercos,
    outerexp,
    outersin,
    outertan,
    power,
    regressive_product,
    reverse,
    right_complement,
    right_contraction,
    right_hodge_dual,
    right_interior_product,
    right_weight_dual,
    rotor_generator,
    sandwich,
    scalar_divide,
    scalar_multiply,
    scalar_part,
    scalar_product,
    scalar_sqrt,
    sqrt,
    squared,
    subtract,
    transwedge,
    transwedge_antiproduct,
    uncomplement,
    undual,
    unit,
)
from .catalog import (
    EXCLUDED_PUBLIC_NAMES,
    OPERATIONS,
    FixedCall,
    LeftFoldCall,
    OperationSpec,
    ParameterSpec,
    get_operation,
)

gp = geometric_product
op = outer_product
dorst_inner = doran_lasenby_inner
join = outer_product
meet = regressive_product
rev = reverse
sw = sandwich
wedge = outer_product

OPERATION_ALIASES = MappingProxyType(
    {
        "conjugate": "clifford_conjugate",
        "dorst_inner": "doran_lasenby_inner",
        "gp": "geometric_product",
        "join": "outer_product",
        "meet": "regressive_product",
        "op": "outer_product",
        "rev": "reverse",
        "sw": "sandwich",
        "wedge": "outer_product",
    }
)
"""Compatibility operation names mapped to canonical facade identifiers."""


def __getattr__(name: str) -> object:
    if name in {"inner_product", "ip"}:
        raise AttributeError(
            f"galaga.facade has no {name!r}: Galaga 2 does not select an ambiguous inner product; "
            "import doran_lasenby_inner, hestenes_inner, metric_inner_product, scalar_product, "
            "left_contraction, or right_contraction explicitly"
        )
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


__all__ = [
    "Algebra",
    "BasisMultivectors",
    "LocalMultivectors",
    "AlgebraConfig",
    "AlgebraDefinition",
    "BladeConvention",
    "BladeLabel",
    "BladeLiteral",
    "BladeRef",
    "Call",
    "CGAPreset",
    "ComplexPreset",
    "ConfiguredPreset",
    "DisplayOrder",
    "DisplayPolicy",
    "EXCLUDED_PUBLIC_NAMES",
    "EuclideanPreset",
    "Expr",
    "Expression",
    "ExteriorPreset",
    "FixedCall",
    "LengyelCGAPreset",
    "LengyelRGAPreset",
    "ObliquePlanePreset",
    "LeftFoldCall",
    "LocalNamePolicy",
    "ModelConfig",
    "Multivector",
    "MultivectorLiteral",
    "Name",
    "Notation",
    "NotationPatch",
    "OPERATION_ALIASES",
    "OPERATIONS",
    "OperationSpec",
    "ParameterSpec",
    "PGAPreset",
    "PresentationConfig",
    "PresentationRecipe",
    "PresentedMultivector",
    "Presenter",
    "RenderRule",
    "Preset",
    "QuaternionPreset",
    "ScalarLiteral",
    "SpacetimePreset",
    "Symbol",
    "add",
    "anticommutator",
    "antidot_product",
    "antimetric_apply",
    "antireverse",
    "antiwedge",
    "build_render_tree",
    "commutator",
    "complex_blade_convention",
    "complement",
    "clifford_conjugate",
    "conjugate",
    "doran_lasenby_inner",
    "divide",
    "dorst_inner",
    "default_blade_convention",
    "default_presentation",
    "dual",
    "euclidean_blade_convention",
    "exterior_blade_convention",
    "even_grades",
    "evaluate",
    "exp",
    "geometric_antiproduct",
    "geometric_product",
    "gp",
    "get_operation",
    "grade",
    "grade_involution",
    "grades",
    "half_anticommutator",
    "half_commutator",
    "hestenes_inner",
    "inverse",
    "indexed_blade_convention",
    "is_basis_blade",
    "is_bivector",
    "is_even",
    "is_rotor",
    "is_rotor_generator",
    "is_scalar",
    "is_vector",
    "jordan_product",
    "join",
    "lengyel_cga_blade_convention",
    "lengyel_cga_display_order",
    "left_complement",
    "left_contraction",
    "left_hodge_dual",
    "left_interior_product",
    "left_weight_dual",
    "lie_bracket",
    "log",
    "meet",
    "metric_apply",
    "metric_inner_product",
    "metric_regressive_product",
    "negate",
    "norm",
    "norm2",
    "null_cga_blade_convention",
    "odd_grades",
    "op",
    "orthogonal_cga_blade_convention",
    "outercos",
    "outerexp",
    "outer_product",
    "outersin",
    "outertan",
    "power",
    "pga_blade_convention",
    "quaternion_blade_convention",
    "quaternion_display_order",
    "regressive_product",
    "render",
    "rga_blade_convention",
    "rga_display_order",
    "rev",
    "reverse",
    "right_complement",
    "right_contraction",
    "right_hodge_dual",
    "right_interior_product",
    "right_weight_dual",
    "rotor_generator",
    "sandwich",
    "scalar_divide",
    "scalar_multiply",
    "scalar_part",
    "scalar_product",
    "scalar_sqrt",
    "sqrt",
    "simplify",
    "spacetime_blade_convention",
    "squared",
    "subtract",
    "sw",
    "transwedge",
    "transwedge_antiproduct",
    "uncomplement",
    "undual",
    "unit",
    "wedge",
]
