"""Core-backed eager numeric facade for Galaga 2.

Importing top-level :mod:`galaga` continues to expose the v1 implementation
until the presentation and expression layers are ready for cutover.  This
namespace is the stable implementation owner; :mod:`galaga.gram_bridge` is a
temporary compatibility re-export of these same objects.
"""

from types import MappingProxyType

from ._numeric import (
    Algebra,
    Multivector,
    anticommutator,
    antidot_product,
    antimetric_apply,
    antireverse,
    antiwedge,
    bulk_part,
    commutator,
    complement,
    conjugate,
    doran_lasenby_inner,
    dual,
    even_grades,
    exp,
    geometric_antiproduct,
    geometric_product,
    grade,
    grade_involution,
    grades,
    half_anticommutator,
    half_commutator,
    hestenes_inner,
    inverse,
    involute,
    is_basis_blade,
    is_bivector,
    is_even,
    is_rotor,
    is_scalar,
    is_vector,
    jordan_product,
    left_complement,
    left_contraction,
    left_hodge_dual,
    left_interior_product,
    left_weight_dual,
    lie_bracket,
    log,
    metric_apply,
    metric_inner_product,
    metric_regressive_product,
    norm,
    norm2,
    odd_grades,
    outer_product,
    outercos,
    outerexp,
    outersin,
    outertan,
    regressive_product,
    reverse,
    right_complement,
    right_contraction,
    right_hodge_dual,
    right_interior_product,
    right_weight_dual,
    sandwich,
    scalar_part,
    scalar_product,
    scalar_sqrt,
    sqrt,
    squared,
    transwedge,
    transwedge_antiproduct,
    uncomplement,
    undual,
    unit,
    weight_part,
)
from .catalog import (
    EXCLUDED_PUBLIC_NAMES,
    OPERATIONS,
    FixedCall,
    LeftFoldCall,
    OperationSpec,
    get_operation,
)

gp = geometric_product
op = outer_product
dorst_inner = doran_lasenby_inner
join = outer_product
meet = regressive_product
rev = reverse
sw = sandwich
wedge = outer_product

OPERATION_ALIASES = MappingProxyType(
    {
        "dorst_inner": "doran_lasenby_inner",
        "gp": "geometric_product",
        "involute": "grade_involution",
        "join": "outer_product",
        "meet": "regressive_product",
        "op": "outer_product",
        "rev": "reverse",
        "sw": "sandwich",
        "wedge": "outer_product",
    }
)
"""Compatibility operation names mapped to canonical facade identifiers."""

__all__ = [
    "Algebra",
    "EXCLUDED_PUBLIC_NAMES",
    "FixedCall",
    "LeftFoldCall",
    "Multivector",
    "OPERATION_ALIASES",
    "OPERATIONS",
    "OperationSpec",
    "anticommutator",
    "antidot_product",
    "antimetric_apply",
    "antireverse",
    "antiwedge",
    "bulk_part",
    "commutator",
    "complement",
    "conjugate",
    "doran_lasenby_inner",
    "dorst_inner",
    "dual",
    "even_grades",
    "exp",
    "geometric_antiproduct",
    "geometric_product",
    "gp",
    "get_operation",
    "grade",
    "grade_involution",
    "grades",
    "half_anticommutator",
    "half_commutator",
    "hestenes_inner",
    "inverse",
    "involute",
    "is_basis_blade",
    "is_bivector",
    "is_even",
    "is_rotor",
    "is_scalar",
    "is_vector",
    "jordan_product",
    "join",
    "left_complement",
    "left_contraction",
    "left_hodge_dual",
    "left_interior_product",
    "left_weight_dual",
    "lie_bracket",
    "log",
    "meet",
    "metric_apply",
    "metric_inner_product",
    "metric_regressive_product",
    "norm",
    "norm2",
    "odd_grades",
    "op",
    "outercos",
    "outerexp",
    "outer_product",
    "outersin",
    "outertan",
    "regressive_product",
    "rev",
    "reverse",
    "right_complement",
    "right_contraction",
    "right_hodge_dual",
    "right_interior_product",
    "right_weight_dual",
    "sandwich",
    "scalar_part",
    "scalar_product",
    "scalar_sqrt",
    "sqrt",
    "squared",
    "sw",
    "transwedge",
    "transwedge_antiproduct",
    "uncomplement",
    "undual",
    "unit",
    "wedge",
    "weight_part",
]
