import marimo

__generated_with = "0.23.11"
app = marimo.App()


@app.cell
def _():
    import sys
    from pathlib import Path

    _repository = Path(__file__).resolve().parent.parent.parent
    for _source in (
        _repository,
        _repository / "packages" / "galaga",
        _repository / "packages" / "galaga_marimo",
        _repository / "packages" / "galaga_mermaid",
    ):
        _path = str(_source)
        if _path not in sys.path:
            sys.path.insert(0, _path)
    return


@app.cell
def _():
    import marimo as mo

    import galaga_marimo as gm
    from galaga import (
        Algebra,
        DisplayPolicy,
        Notation,
        exp,
        p_euclidean,
        sandwich,
    )
    from galaga_mermaid import expr_to_mermaid, mv_to_mermaid

    return (
        Algebra,
        DisplayPolicy,
        Notation,
        exp,
        expr_to_mermaid,
        gm,
        mo,
        mv_to_mermaid,
        p_euclidean,
        sandwich,
    )


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    # Mermaid diagrams from Galaga expressions

    `galaga_mermaid` turns Galaga 2's immutable expression provenance into
    Mermaid flowcharts. The diagram is another view of an expression: changing
    its direction, detail, labels, or value annotations does not change the
    multivector or its expression tree.

    This notebook uses Marimo's `mo.mermaid(...)` component to render the text
    generated by `galaga_mermaid`.
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Build an expression worth inspecting

    We construct a vector $u$, a named rotation plane $B$, and a rotor

    $$
    R=\exp\!\left(-\frac{\theta B}{2}\right).
    $$

    The final sandwich $Ru\widetilde R$ retains the operations needed to build
    a provenance diagram. Named inputs become reusable symbol leaves.
    """)
    return


@app.cell
def _(Algebra, DisplayPolicy, exp, p_euclidean, sandwich):
    algebra = Algebra(
        config=p_euclidean(3),
        display=DisplayPolicy(content="full"),
    )
    e1, e2, e3 = algebra.basis_vectors(expr=True)
    u = (2 * e1 + e2).named("u")
    rotation_plane = (e1 ^ e2).named("B")
    theta = algebra.scalar(0.6).named("theta", latex=r"\theta")
    rotor = exp(-theta * rotation_plane / 2)
    rotated_u = sandwich(rotor, u).named("u_prime", latex=r"u^{\prime}")
    return algebra, rotated_u, rotation_plane, rotor, theta, u


@app.cell
def _(gm, rotated_u, rotation_plane, rotor, theta, u):
    gm.md(rt"""
    Inputs:

    {u}

    {rotation_plane}

    {theta}

    Rotor and result:

    {rotor}

    {rotated_u}
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## `mv_to_mermaid`: start from a facade value

    `mv_to_mermaid(value)` derives the algebra, active presentation, and
    expression from the multivector. Named symbol leaves still need concrete
    values in `environment=` if their numeric values should appear in node
    labels.

    The controls below regenerate only the Mermaid text.
    """)
    return


@app.cell
def _(mo):
    diagram_direction = mo.ui.dropdown(
        options=["TD", "LR", "BT", "RL"],
        value="LR",
        label="direction",
    )
    compact_diagram = mo.ui.switch(value=False, label="compact tree")
    annotate_values = mo.ui.switch(value=True, label="show values")
    mo.hstack([diagram_direction, compact_diagram, annotate_values])
    return annotate_values, compact_diagram, diagram_direction


@app.cell
def _(
    annotate_values,
    compact_diagram,
    diagram_direction,
    mo,
    mv_to_mermaid,
    rotated_u,
    rotation_plane,
    theta,
    u,
):
    symbol_environment = {
        "u": u,
        "B": rotation_plane,
        "theta": theta,
    }
    interactive_mermaid = mv_to_mermaid(
        rotated_u,
        direction=diagram_direction.value,
        compact=compact_diagram.value,
        show_values=annotate_values.value,
        environment=symbol_environment,
    )
    mo.mermaid(interactive_mermaid)
    return interactive_mermaid, symbol_environment


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    Expanded mode keeps intermediate calls such as negation, multiplication,
    division, exponential, and sandwich. Compact mode connects the significant
    literal and symbol descendants directly to each retained call.

    Node colors are emitted by `galaga_mermaid`: symbols, blade literals, and
    scalar/multivector literals have distinct styles.
    """)
    return


@app.cell
def _(interactive_mermaid, mo):
    mo.accordion(
        {
            "Generated Mermaid source": mo.md(
                f"""```text
    {interactive_mermaid}
    ```"""
            )
        }
    )
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## `expr_to_mermaid`: provide dependencies explicitly

    An `Expr` deliberately stores neither an algebra nor captured symbol
    values. The lower-level API therefore requires a presentation, and value
    annotations additionally require the algebra and symbol environment.

    This separation lets the same expression be diagrammed using another
    notation without rebuilding or reevaluating it.
    """)
    return


@app.cell
def _(Notation, algebra, expr_to_mermaid, rotated_u, symbol_environment):
    short_functional_presentation = algebra.presentation.with_notation(
        Notation.functional(short=True)
    )
    functional_mermaid = expr_to_mermaid(
        rotated_u.expr,
        presentation=short_functional_presentation,
        direction="TD",
        show_values=True,
        algebra=algebra,
        environment=symbol_environment,
    )
    return (functional_mermaid,)


@app.cell
def _(functional_mermaid, mo):
    mo.mermaid(functional_mermaid, theme="neutral")
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    The second diagram uses short functional labels such as `sw(...)`, `gp(...)`,
    and `rev(...)` where those operations occur. The expression identity is
    unchanged; only the presentation used for node labels differs.

    In application code:

    ```python
    source = mv_to_mermaid(value)
    source = expr_to_mermaid(
        value.expr,
        presentation=value.algebra.presentation,
    )
    ```

    Both functions return ordinary Mermaid source text, so it can be embedded
    by Marimo, documentation tooling, or any Mermaid-capable frontend.
    """)
    return


if __name__ == "__main__":
    app.run()
