"""galaga_annotation — semantic annotations and KaTeX rendering for galaga.

Immutable rules, callable annotators, and a first KaTeX renderer for
expressions, values and multivector components. This package is optional:
importing ``galaga`` never imports ``galaga_annotation``.
"""

from .annotator import Annotator, annotate, annotator
from .cga import CGAObject, HighlightDecomposition, OverMarker, cga_parts, classify_cga, highlight_cga, highlight_object
from .katex import KatexResult, LabelPlacement, SpanLayoutError, render_katex
from .matrix import (
    AnnotatedMatrix,
    MatrixKatexResult,
    MatrixPlacement,
    MatrixPlan,
    is_matrix,
    render_matrix_katex,
    resolve_matrix,
)
from .model import Annotation, AnnotationStyle, on
from .plan import AnnotationPlan, MissingTargetError, Placement, resolve
from .presenter import AnnotationPresenter
from .targets import (
    ANNOTATION_TARGET_TYPES,
    MATRIX_TARGET_TYPES,
    CoefficientTarget,
    ContentKind,
    ContentTarget,
    ExpressionPath,
    GradeTarget,
    MatrixAxis,
    MatrixCell,
    MatrixRegion,
    OperationTarget,
    SignTarget,
    SubexpressionTarget,
    TermTarget,
    VariableTarget,
    WholeExpression,
    blade_mask,
    block,
    cell,
    coefficient,
    coefficients,
    column,
    content,
    grade,
    grades,
    operand,
    operator,
    path,
    resolve_axis,
    row,
    sign,
    signs,
    subexpression,
    term,
    terms,
    variable,
    whole,
)
from .view import Annotated

__all__ = [
    "ANNOTATION_TARGET_TYPES",
    "MATRIX_TARGET_TYPES",
    "Annotation",
    "AnnotationPlan",
    "AnnotationPresenter",
    "AnnotationStyle",
    "Annotated",
    "AnnotatedMatrix",
    "Annotator",
    "CGAObject",
    "CoefficientTarget",
    "ContentKind",
    "ContentTarget",
    "ExpressionPath",
    "GradeTarget",
    "HighlightDecomposition",
    "KatexResult",
    "LabelPlacement",
    "MatrixAxis",
    "MatrixCell",
    "MatrixKatexResult",
    "MatrixPlacement",
    "MatrixPlan",
    "MatrixRegion",
    "MissingTargetError",
    "OperationTarget",
    "OverMarker",
    "Placement",
    "SignTarget",
    "SpanLayoutError",
    "SubexpressionTarget",
    "TermTarget",
    "VariableTarget",
    "WholeExpression",
    "annotate",
    "annotator",
    "blade_mask",
    "block",
    "cell",
    "cga_parts",
    "classify_cga",
    "coefficient",
    "coefficients",
    "column",
    "content",
    "grade",
    "grades",
    "highlight_cga",
    "highlight_object",
    "is_matrix",
    "on",
    "operand",
    "operator",
    "path",
    "render_katex",
    "render_matrix_katex",
    "resolve",
    "resolve_axis",
    "resolve_matrix",
    "row",
    "sign",
    "signs",
    "subexpression",
    "term",
    "terms",
    "variable",
    "whole",
]
