"""Experimental numeric Galaga facade backed by :mod:`gram`.

The bridge is deliberately opt-in during migration.  Importing ``galaga``
continues to expose the current implementation until the compatibility and
presentation layers are ready for cutover.
"""

from .catalog import (
    EXCLUDED_PUBLIC_NAMES,
    OPERATIONS,
    FixedCall,
    LeftFoldCall,
    OperationSpec,
    get_operation,
)
from .facade import (
    Algebra,
    Multivector,
    anticommutator,
    commutator,
    complement,
    conjugate,
    doran_lasenby_inner,
    dual,
    exp,
    geometric_product,
    grade,
    grades,
    half_anticommutator,
    half_commutator,
    hestenes_inner,
    inverse,
    involute,
    left_contraction,
    log,
    metric_inner_product,
    norm,
    norm2,
    outer_product,
    reverse,
    right_contraction,
    scalar_part,
    scalar_product,
    squared,
    unit,
)

__all__ = [
    "Algebra",
    "EXCLUDED_PUBLIC_NAMES",
    "FixedCall",
    "LeftFoldCall",
    "Multivector",
    "OPERATIONS",
    "OperationSpec",
    "anticommutator",
    "commutator",
    "complement",
    "conjugate",
    "doran_lasenby_inner",
    "dual",
    "exp",
    "geometric_product",
    "get_operation",
    "grade",
    "grades",
    "half_anticommutator",
    "half_commutator",
    "hestenes_inner",
    "inverse",
    "involute",
    "left_contraction",
    "log",
    "metric_inner_product",
    "norm",
    "norm2",
    "outer_product",
    "reverse",
    "right_contraction",
    "scalar_part",
    "scalar_product",
    "squared",
    "unit",
]
