"""ga - A geometric algebra library with a stable, programmer-first API."""

from ga.algebra import (
    Algebra,
    Multivector,
    # Core operations
    gp,
    op,
    left_contraction,
    right_contraction,
    hestenes_inner,
    scalar_product,
    commutator,
    anticommutator,
    # Unary
    reverse,
    involute,
    conjugate,
    grade,
    grades,
    scalar,
    dual,
    undual,
    norm2,
    norm,
    unit,
    inverse,
    # Predicates
    is_scalar,
    is_vector,
    is_bivector,
    is_even,
    is_rotor,
    even_grades,
    odd_grades,
    even,
    odd,
    squared,
    sandwich,
    sw,
    norm_squared,
    # Aliases
    geometric_product,
    wedge,
    outer_product,
    rev,
    normalize,
    normalise,
    ip,
    inner_product,
)

__all__ = [
    "Algebra",
    "Multivector",
    "gp",
    "op",
    "left_contraction",
    "right_contraction",
    "hestenes_inner",
    "scalar_product",
    "commutator",
    "anticommutator",
    "reverse",
    "involute",
    "conjugate",
    "grade",
    "grades",
    "scalar",
    "dual",
    "undual",
    "norm2",
    "norm",
    "unit",
    "inverse",
    "is_scalar",
    "is_vector",
    "is_bivector",
    "is_even",
    "is_rotor",
    "even_grades",
    "odd_grades",
    "even",
    "odd",
    "squared",
    "sandwich",
    "sw",
    "geometric_product",
    "wedge",
    "outer_product",
    "rev",
    "normalize",
    "normalise",
    "norm_squared",
    "ip",
    "inner_product",
]
