import marimo

__generated_with = "0.21.1"
app = marimo.App()


@app.cell
def _():
    import sys
    from pathlib import Path

    _root = str(Path(__file__).resolve().parent.parent)
    _gamo = str(Path(__file__).resolve().parent.parent / "packages" / "galaga_marimo")
    for p in [_root, _gamo]:
        if p not in sys.path:
            sys.path.insert(0, p)
    return


@app.cell
def _():
    import marimo as mo
    import numpy as np
    import matplotlib.pyplot as plt
    import matplotlib

    matplotlib.rcParams.update({"figure.facecolor": "white"})

    from galaga import Algebra, exp, scalar
    import galaga_marimo as gm

    return Algebra, exp, gm, mo, np, plt, scalar


@app.cell(hide_code=True)
def _(mo):
    mo.md("""
    # Aharonov-Bohm Holonomy

    The Aharonov-Bohm effect is best understood as a holonomy problem. A charged
    wavefunction moves around a region where the field vanishes locally, but the
    loop still encloses nontrivial magnetic flux. The gauge potential contributes
    a path-dependent phase, and the closed-loop holonomy is observable.

    This notebook treats that phase as an internal geometric-algebra rotor
    generated by the spacetime pseudoscalar.
    """)
    return


@app.cell
def _(Algebra):
    sta = Algebra((1, -1, -1, -1), names="gamma", repr_unicode=True)
    g0, g1, g2, g3 = sta.basis_vectors(lazy=True)
    I = sta.I.name("I")
    return (I,)


@app.cell
def _(I, gm, scalar):
    gm.md(t"""
    ## Internal Phase Rotor

    {I} = {I.eval()}

    $I^2 = {scalar((I * I).eval()):+.0f}$

    In STA the usual complex phase factor $e^{{i\\phi}}$ is replaced by an even
    multivector rotor $e^{{-I\\phi/2}}$.
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md("""
    ## Holonomy Around a Flux Tube

    For a loop encircling flux `Φ`, the total phase is

    $$
    \Delta \phi =     rac{q}{\hbar} \oint A \cdot dl =     rac{q \Phi}{\hbar}.
    $$

    The physics lives in the closed-loop quantity, not in any one segment by
    itself. That is why the effect is naturally described as holonomy.
    """)
    return


@app.cell
def _(mo):
    flux = mo.ui.slider(start=0.0, stop=4.0, step=0.01, value=1.0, label="enclosed flux Φ / π")
    asymmetry = mo.ui.slider(start=0.0, stop=1.0, step=0.01, value=0.5, label="fraction of loop on upper path")
    mo.vstack([flux, asymmetry])
    return asymmetry, flux


@app.cell
def _(I, asymmetry, exp, flux, gm, np):
    delta_phi = flux.value * np.pi
    upper_phi = asymmetry.value * delta_phi
    lower_phi = -(1.0 - asymmetry.value) * delta_phi
    upper_rotor = exp((-upper_phi / 2) * I).name(latex=r"R_{\mathrm{upper}}")
    lower_rotor = exp((-lower_phi / 2) * I).name(latex=r"R_{\mathrm{lower}}")
    holonomy = (upper_rotor * ~lower_rotor).name("H", latex=r"\mathcal{H}")
    interference = 0.5 * (1 + np.cos(delta_phi))

    gm.md(t"""
    {upper_rotor} = {upper_rotor.eval()}

    {lower_rotor} = {lower_rotor.eval()}

    {holonomy} = {holonomy.eval()}

    The observable phase difference is $\\Delta \\phi = {delta_phi / np.pi:.3f}\\pi$.

    Interference visibility: $P = \\frac{{1 + \\cos \\Delta\\phi}}{{2}} = {interference:.4f}$
    """)
    return delta_phi, interference


@app.cell(hide_code=True)
def _(mo):
    mo.md("""
    ## Geometric Picture

    The two open paths are gauge-dependent. The closed loop around the flux tube
    is gauge-invariant, and its rotor records the holonomy.
    """)
    return


@app.cell
def _(asymmetry, delta_phi, interference, np, plt):
    _fig, (_ax1, _ax2) = plt.subplots(1, 2, figsize=(11, 4.5))

    _theta = np.linspace(0, 2 * np.pi, 200)
    _ax1.fill(0.35 * np.cos(_theta), 0.35 * np.sin(_theta), color="steelblue", alpha=0.25)
    _ax1.text(0, 0, r"$\Phi_B$", ha="center", va="center", color="steelblue", fontsize=13)

    _split = asymmetry.value
    _upper = np.linspace(np.pi, 0, max(20, int(220 * _split)))
    _lower = np.linspace(np.pi, 2 * np.pi, max(20, int(220 * (1 - _split))))
    _ax1.plot(1.7 * np.cos(_upper), 1.1 * np.sin(_upper), color="crimson", linewidth=2.5)
    _ax1.plot(1.7 * np.cos(_lower), 1.1 * np.sin(_lower), color="seagreen", linewidth=2.5)
    _ax1.plot([-1.7], [0], "ks", ms=9)
    _ax1.plot([1.7], [0], "k^", ms=10)
    _ax1.text(-1.7, -0.25, "source", ha="center")
    _ax1.text(1.7, -0.25, "detector", ha="center")
    _ax1.set_aspect("equal")
    _ax1.set_xlim(-2.1, 2.1)
    _ax1.set_ylim(-1.5, 1.5)
    _ax1.set_title("Two paths around the solenoid")
    _ax1.axis("off")

    _phis = np.linspace(0, 4 * np.pi, 500)
    _prob = 0.5 * (1 + np.cos(_phis))
    _ax2.plot(_phis / np.pi, _prob, color="darkorange", linewidth=2.5)
    _ax2.plot(delta_phi / np.pi, interference, "ko", ms=8)
    _ax2.set_xlabel(r"$\Delta\phi / \pi$")
    _ax2.set_ylabel("detector probability")
    _ax2.set_xlim(0, 4)
    _ax2.set_ylim(-0.05, 1.05)
    _ax2.set_title("Holonomy controls interference")
    _ax2.grid(True, alpha=0.2)
    _fig.tight_layout()
    _fig
    return


@app.cell
def _():
    return


if __name__ == "__main__":
    app.run()
