import marimo

__generated_with = "0.21.1"
app = marimo.App()


@app.cell
def _():
    import sys
    from pathlib import Path

    _root = str(Path(__file__).resolve().parent.parent)
    _gamo = str(Path(__file__).resolve().parent.parent / "packages" / "gamo")
    for p in [_root, _gamo]:
        if p not in sys.path:
            sys.path.insert(0, p)
    return


@app.cell
def _():
    import marimo as mo

    return (mo,)


@app.cell
def _():
    import numpy as np
    import matplotlib.pyplot as plt
    import matplotlib

    matplotlib.rcParams.update({"figure.facecolor": "white"})

    from ga import Algebra, scalar, grade, exp, sandwich
    import galaga_marimo as gm

    return Algebra, exp, gm, grade, np, plt, sandwich, scalar


@app.cell(hide_code=True)
def _(gm):
    gm.md(t"""
    # The Aharonov–Bohm Effect in Spacetime Algebra

    The Aharonov–Bohm effect demonstrates that the electromagnetic **potential**
    $A$ has physical consequences even where the field $F = 0$. A charged particle
    acquires a phase shift from the potential alone.

    In the GA approach, this phase is a **rotor** — a U(1) rotation generated by
    the pseudoscalar $I = e_0 e_1 e_2 e_3$.

    $$\\psi \\to \\psi' = e^{{-q\\Phi I}} \\, \\psi$$

    where $\\Phi = \\oint A \\cdot dl$ is the magnetic flux enclosed by the path.
    """)
    return


@app.cell(hide_code=True)
def _(gm):
    gm.md(t"""
    ## The Algebra

    We work in the Spacetime Algebra Cl(1,3). The pseudoscalar $I$ squares to
    $-1$ and commutes with even elements — it plays the role of the imaginary
    unit $i$ in the conventional QM phase factor $e^{{i\\phi}}$.
    """)
    return


@app.cell
def _(Algebra, gm, scalar):
    sta = Algebra((1, -1, -1, -1), names="gamma", repr_unicode=True)
    g0, g1, g2, g3 = sta.basis_vectors()
    I = sta.I

    gm.md(t"""**Spacetime Algebra** Cl(1,3):
- $I = {I}$, $\\quad I^2 = {scalar(I * I):text}$
- $I$ commutes with all even elements ✓
- $I$ generates U(1) phase rotations""")
    return I, g0, g1, g2, g3, sta


@app.cell(hide_code=True)
def _(gm):
    gm.md(t"""
    ## U(1) Phase as a Rotor

    In conventional QM, a phase factor is $e^{{i\\phi}}$. In STA, the
    pseudoscalar $I$ replaces $i$, and the phase factor becomes a rotor:

    $$R(\\phi) = e^{{-\\phi I/2}} = \\cos(\\phi/2) - \\sin(\\phi/2)\\,I$$

    This is a rotation in the $I$-plane — a U(1) transformation that leaves
    the spin vector unchanged but rotates the rotor's overall phase.
    """)
    return


@app.cell
def _(I, gm, mo, np, scalar, sta):
    _phases = [0, np.pi / 4, np.pi / 2, np.pi, 2 * np.pi]
    _rows = []
    for phi in _phases:
        R = sta.rotor(I, radians=phi)
        RR = scalar(R * ~R)
        _rows.append(f"| ${phi / np.pi:.2f}\\pi$ | {R.latex(wrap='$')} | ${RR:.4f}$ |")

    gm.md(t"""| Phase $\\phi$ | Rotor $R(\\phi)$ | $R\\tilde{{R}}$ |
|---|---|---|
{"\n".join(_rows):text}

At $\\phi = 2\\pi$: the rotor is $-1$ (sign flip), just like the spinor double cover.
At $\\phi = 4\\pi$: the rotor returns to $+1$.""")
    return


@app.cell(hide_code=True)
def _(gm):
    gm.md(t"""
    ## The Aharonov–Bohm Setup

    A solenoid carries magnetic flux $\\Phi$. Two electron paths go around
    opposite sides of the solenoid and recombine. Outside the solenoid,
    $F = 0$ everywhere — but $A \\neq 0$.

    Each path accumulates a phase from the line integral of $A$:
    - Path 1 (above): $\\phi_1 = q \\int_1 A \\cdot dl$
    - Path 2 (below): $\\phi_2 = q \\int_2 A \\cdot dl$

    The phase difference is $\\Delta\\phi = q \\oint A \\cdot dl = q\\Phi$ (by Stokes' theorem).

    In GA, each path produces a rotor, and the interference depends on the
    relative rotor $R_1 \\tilde{{R}}_2$.
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    flux_slider = mo.ui.slider(
        start=0.0, stop=4.0, step=0.01, value=1.0,
        label="Magnetic flux Φ (units of π)"
    )
    flux_slider
    return (flux_slider,)


@app.cell
def _(I, flux_slider, gm, mo, np, scalar, sta):
    _Phi = flux_slider.value * np.pi  # total enclosed flux

    # Phase accumulated by each path (symmetric split)
    _phi1 = _Phi / 2    # path above
    _phi2 = -_Phi / 2   # path below

    _R1 = sta.rotor(I, radians=_phi1)
    _R2 = sta.rotor(I, radians=_phi2)

    # Relative phase
    _R_rel = _R1 * ~_R2
    _phase_diff = _Phi  # total phase difference

    # Interference: probability ~ |ψ₁ + ψ₂|² ~ 1 + cos(ΔΦ)
    _prob = (1 + np.cos(_phase_diff)) / 2

    mo.vstack([
        gm.md(t"$\\Phi = {flux_slider.value:.2f}\\pi$"),
        gm.md(t"Path 1 rotor: {_R1}"),
        gm.md(t"Path 2 rotor: {_R2}"),
        gm.md(t"Relative rotor $R_1 \\tilde{{R}}_2$: {_R_rel}"),
        gm.md(t"Phase difference: $\\Delta\\phi = {_phase_diff:.4f}$ rad"),
        gm.md(t"**Interference: $P = {_prob:.4f}$**"),
    ])
    return


@app.cell(hide_code=True)
def _(flux_slider, np, plt):
    _Phi_range = np.linspace(0, 4 * np.pi, 500)
    _prob_curve = (1 + np.cos(_Phi_range)) / 2
    _current_Phi = flux_slider.value * np.pi
    _current_prob = (1 + np.cos(_current_Phi)) / 2

    _fig, _ax = plt.subplots(figsize=(8, 4))
    _ax.plot(_Phi_range / np.pi, _prob_curve, "crimson", lw=2.5)
    _ax.plot(_current_Phi / np.pi, _current_prob, "ko", ms=10, zorder=5)
    _ax.axhline(0.5, color="gray", ls=":", alpha=0.3)
    _ax.set_xlabel("Magnetic flux $\\Phi$ (units of $\\pi$)", fontsize=12)
    _ax.set_ylabel("Detection probability $P$", fontsize=12)
    _ax.set_title("Aharonov–Bohm Interference Pattern", fontsize=13)
    _ax.set_xlim(0, 4)
    _ax.set_ylim(-0.05, 1.05)
    _ax.grid(True, alpha=0.2)

    # Mark key points
    for n, label in [(0, "constructive"), (1, "destructive"), (2, "constructive")]:
        _ax.annotate(label, xy=(n, (1 + np.cos(n * np.pi)) / 2),
                     xytext=(n + 0.15, 0.85 if n % 2 == 0 else 0.15),
                     fontsize=9, alpha=0.6,
                     arrowprops=dict(arrowstyle="->", alpha=0.4))

    plt.tight_layout()
    _fig
    return


@app.cell(hide_code=True)
def _(gm):
    gm.md(t"""
    ## The Geometric Picture

    The diagram below shows the two paths around the solenoid. The rotor
    accumulated along each path is a U(1) phase rotation generated by $I$.
    """)
    return


@app.cell(hide_code=True)
def _(flux_slider, np, plt):
    _fig, _ax = plt.subplots(figsize=(6, 6))

    # Solenoid (center)
    _theta = np.linspace(0, 2 * np.pi, 100)
    _ax.fill(0.3 * np.cos(_theta), 0.3 * np.sin(_theta), color="steelblue", alpha=0.3)
    _ax.text(0, 0, "$\\Phi$", ha="center", va="center", fontsize=14, color="steelblue")

    # Path 1 (above)
    _t1 = np.linspace(0, np.pi, 100)
    _ax.plot(1.5 * np.cos(_t1), 1.5 * np.sin(_t1), "crimson", lw=2.5, label="Path 1")
    _ax.annotate("", xy=(-0.1, 1.5), xytext=(0.1, 1.5),
                 arrowprops=dict(arrowstyle="->", color="crimson", lw=2))

    # Path 2 (below)
    _t2 = np.linspace(np.pi, 2 * np.pi, 100)
    _ax.plot(1.5 * np.cos(_t2), 1.5 * np.sin(_t2), "seagreen", lw=2.5, label="Path 2")
    _ax.annotate("", xy=(0.1, -1.5), xytext=(-0.1, -1.5),
                 arrowprops=dict(arrowstyle="->", color="seagreen", lw=2))

    # Source and detector
    _ax.plot(-1.5, 0, "ks", ms=12)
    _ax.text(-1.5, -0.3, "source", ha="center", fontsize=10)
    _ax.plot(1.5, 0, "k^", ms=12)
    _ax.text(1.5, -0.3, "detector", ha="center", fontsize=10)

    # Phase labels
    _phi_val = flux_slider.value * np.pi / 2
    _ax.text(0, 1.8, f"$\\phi_1 = +{_phi_val / np.pi:.2f}\\pi$",
             ha="center", fontsize=11, color="crimson")
    _ax.text(0, -1.8, f"$\\phi_2 = -{_phi_val / np.pi:.2f}\\pi$",
             ha="center", fontsize=11, color="seagreen")

    _ax.set_xlim(-2.5, 2.5)
    _ax.set_ylim(-2.5, 2.5)
    _ax.set_aspect("equal")
    _ax.legend(loc="upper right", fontsize=10)
    _ax.set_title("Aharonov–Bohm: Two Paths Around a Solenoid", fontsize=13)
    _ax.grid(True, alpha=0.1)
    plt.tight_layout()
    _fig
    return


@app.cell(hide_code=True)
def _(gm):
    gm.md(t"""
    ## Key Insight

    The electromagnetic field $F = 0$ everywhere outside the solenoid. Yet the
    potential $A$ is nonzero, and the phase difference $\\Delta\\phi = q\\Phi$ produces
    observable interference.

    In the GA formulation:
    - The phase is a **rotor** $R = e^{{-q\\Phi I/2}}$, not a complex number
    - The generator is the **pseudoscalar** $I$, not the imaginary unit $i$
    - The double cover is manifest: $\\Phi = 2\\pi$ gives $R = -1$ (sign flip)
    - The interference pattern is $P = \\frac{{1 + \\cos(q\\Phi)}}{{2}}$

    This is the same physics as the conventional treatment, but expressed in the
    real geometric algebra of spacetime — no complex numbers needed.
    """)
    return


@app.cell
def _():
    return


if __name__ == "__main__":
    app.run()
