import marimo

__generated_with = "0.21.1"
app = marimo.App()


@app.cell
def _():
    import sys
    from pathlib import Path

    _root = str(Path(__file__).resolve().parent.parent)
    _gamo = str(Path(__file__).resolve().parent.parent / "packages" / "galaga_marimo")
    for p in [_root, _gamo]:
        if p not in sys.path:
            sys.path.insert(0, p)
    return


@app.cell
def _():
    import marimo as mo
    import numpy as np
    import matplotlib.pyplot as plt
    import matplotlib

    matplotlib.rcParams.update({"figure.facecolor": "white"})

    from galaga import Algebra, dual, norm
    import galaga_marimo as gm

    return Algebra, dual, gm, mo, norm, np, plt


@app.cell(hide_code=True)
def _(mo):
    mo.md("""
    # Exterior Algebra Intuition

    The wedge product is the oriented-content operator inside geometric algebra.
    A vector is an oriented length, a bivector is an oriented area element, and a
    trivector is an oriented volume element.
    """)
    return


@app.cell
def _(Algebra):
    alg = Algebra((1, 1, 1), repr_unicode=True)
    e1, e2, e3 = alg.basis_vectors(lazy=True)
    return e1, e2, e3


@app.cell
def _(e1, e2, e3, gm):
    _u = (2 * e1 + e2).name("u")
    _v = (0.5 * e1 + 1.8 * e2).name("v")
    _w = (e1 + 0.5 * e2 + 1.2 * e3).name("w")
    bivector = (_u ^ _v)
    trivector = (_u ^ _v ^ _w)

    gm.md(t"""
    ## Length, Area, Volume

    {_u} = {_u.eval()}

    {_v} = {_v.eval()}

    {_w} = {_w.eval()}

    {bivector} = {bivector.eval()}

    {trivector} = {trivector.eval()}
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md("""
    ## Interactive Oriented Area

    The sign of `u ∧ v` records orientation. When the two vectors align, the
    bivector collapses to zero.
    """)
    return


@app.cell
def _(mo):
    angle = mo.ui.slider(start=-180, stop=180, step=1, value=45, label="angle of v")
    length = mo.ui.slider(start=0.2, stop=2.0, step=0.05, value=1.2, label="length of v")
    mo.vstack([angle, length])
    return angle, length


@app.cell
def _(angle, dual, e1, e2, gm, length, norm, np):
    u = e1.name("u")
    v = (length.value * (np.cos(np.radians(angle.value)) * e1 + np.sin(np.radians(angle.value)) * e2)).name("v")
    wedge = (u ^ v)
    area = norm(wedge)
    pseudo_cross = dual(wedge)
    
    gm.md(t"""
    {u} = {u.eval()}

    {v} = {v.eval()}

    {wedge} = {wedge.eval()}

    Area of the parallelogram = {area:.4f}

    Dual vector {pseudo_cross} = {pseudo_cross.eval()}
    """)
    return


@app.cell
def _(angle, length, np, plt):
    _theta = np.radians(angle.value)
    _u = np.array([1.0, 0.0])
    _v = length.value * np.array([np.cos(_theta), np.sin(_theta)])
    _fig, _ax = plt.subplots(figsize=(6, 6))
    _ax.quiver(0, 0, _u[0], _u[1], angles="xy", scale_units="xy", scale=1, color="crimson", width=0.012)
    _ax.quiver(0, 0, _v[0], _v[1], angles="xy", scale_units="xy", scale=1, color="steelblue", width=0.012)
    _ax.fill([0, _u[0], _u[0] + _v[0], _v[0]], [0, _u[1], _u[1] + _v[1], _v[1]], color="goldenrod", alpha=0.25)
    _ax.set_aspect("equal")
    _ax.set_xlim(-2.2, 2.2)
    _ax.set_ylim(-2.2, 2.2)
    _ax.set_title("Parallelogram generated by u and v")
    _ax.grid(True, alpha=0.2)
    _fig.tight_layout()
    _fig
    return


@app.cell
def _():
    return


if __name__ == "__main__":
    app.run()
