"""Format-neutral semantic rendering for the Galaga 2 facade."""

from ._build import content_tree, expression_tree, value_tree
from ._emit import emit
from .document import (
    ContentAnchor,
    ExpressionAnchor,
    RenderAnchor,
    RenderDocument,
    content_document,
    expression_document,
    value_document,
)
from .tree import (
    Accent,
    Associativity,
    Call,
    Decorated,
    Delimited,
    Equality,
    Fraction,
    GradeColor,
    Group,
    Identifier,
    Infix,
    Literal,
    MathClass,
    Node,
    Postfix,
    Power,
    Precedence,
    Prefix,
    Product,
    Subscript,
    Sum,
    SumTerm,
    Table,
    Text,
    Underset,
    Wrapper,
    grouped_child,
)

__all__ = [
    "Accent",
    "Associativity",
    "Call",
    "ContentAnchor",
    "Decorated",
    "Delimited",
    "Equality",
    "ExpressionAnchor",
    "Fraction",
    "GradeColor",
    "Group",
    "Identifier",
    "Infix",
    "Literal",
    "MathClass",
    "Node",
    "Postfix",
    "Power",
    "Precedence",
    "Prefix",
    "Product",
    "RenderAnchor",
    "RenderDocument",
    "Subscript",
    "Sum",
    "SumTerm",
    "Table",
    "Text",
    "Underset",
    "Wrapper",
    "content_tree",
    "content_document",
    "emit",
    "expression_tree",
    "expression_document",
    "grouped_child",
    "value_tree",
    "value_document",
]
