import marimo

__generated_with = "0.23.4"
app = marimo.App()


@app.cell
def _():
    import sys
    from pathlib import Path

    _root = str(Path(__file__).resolve().parent.parent.parent)
    _gamo = str(Path(__file__).resolve().parent.parent.parent / "packages" / "galaga_marimo")
    _gmat = str(Path(__file__).resolve().parent.parent.parent / "packages" / "galaga_matrix")
    for _p in [_root, _gamo, _gmat]:
        if _p not in sys.path:
            sys.path.insert(0, _p)
    return


@app.cell
def _():
    import marimo as mo
    import numpy as np

    from galaga import Algebra, b_sta, exp, reverse
    import galaga_marimo as gm
    from galaga_matrix import (
        MatrixRepr,
        QuatMatrixRepr,
        from_spinor_column,
        from_spinor_matrix,
        from_spinor_quaternion,
        to_matrix,
        to_spinor_column,
        to_spinor_matrix,
        to_spinor_quaternion,
    )
    from galaga_matrix.matrix import compact_basis

    return (
        Algebra,
        MatrixRepr,
        QuatMatrixRepr,
        b_sta,
        compact_basis,
        exp,
        from_spinor_column,
        from_spinor_matrix,
        from_spinor_quaternion,
        gm,
        mo,
        np,
        reverse,
        to_matrix,
        to_spinor_column,
        to_spinor_matrix,
        to_spinor_quaternion,
    )


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    # Spinor Column Conversions

    This notebook demonstrates the `galaga_matrix` spinor-column APIs:

    - `to_spinor_column`: even multivector $\psi \mapsto$ complex column
    - `from_spinor_column`: complex column $\mapsto$ even multivector
    - `to_spinor_quaternion`: even multivector $\mapsto$ quaternion column
    - `from_spinor_quaternion`: quaternion column $\mapsto$ even multivector

    The older names `to_spinor_matrix` and `from_spinor_matrix` are still
    available as compatibility aliases, but the mathematical object returned is
    a **column vector**, not an operator matrix.
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## The Shared Idea

    In geometric algebra, a spinor is usually represented inside the algebra as
    an even multivector:

    $$
    \psi \in Cl^0(p,q).
    $$

    In quantum mechanics, a spinor is usually represented as a column vector.
    The conversion in this package chooses a fixed reference column $u$ in a
    matrix representation $\rho$ and maps

    $$
    \operatorname{col}(\psi) = \rho(\psi)u.
    $$

    This is not just a dimension count. For every supported algebra, the library
    builds the real linear system generated by the even basis blades and checks

    $$
    \operatorname{rank}_{\mathbb R} A = \dim_{\mathbb R} Cl^0(p,q).
    $$

    That rank check is what makes the inverse conversion meaningful.
    """)
    return


@app.cell
def _(Algebra):
    cl3 = Algebra((1, 1, 1), repr_unicode=True)
    cl3_e1, cl3_e2, cl3_e3 = cl3.basis_vectors(lazy=True)
    return cl3, cl3_e1, cl3_e2, cl3_e3


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Pauli Spinors from $Cl(3,0)$

    The even subalgebra of $Cl(3,0)$ has four real degrees of freedom:

    $$
    Cl^0(3,0) = \operatorname{span}_{\mathbb R}
    \{1, e_{12}, e_{13}, e_{23}\}.
    $$

    A Pauli spinor has two complex components, also four real degrees of
    freedom. The conversion is therefore capable of being one-to-one, but the
    library still checks the actual rank of the chosen map.
    """)
    return


@app.cell
def _(MatrixRepr, cl3, compact_basis, gm):
    _pauli_gammas = compact_basis(cl3)
    _sigma1 = MatrixRepr(_pauli_gammas[0], label=r"\sigma_1")
    _sigma2 = MatrixRepr(_pauli_gammas[1], label=r"\sigma_2")
    _sigma3 = MatrixRepr(_pauli_gammas[2], label=r"\sigma_3")

    gm.md(t"""
    The compact representation sends the basis vectors of $Cl(3,0)$ to the
    Pauli matrices:

    {_sigma1:block}

    {_sigma2:block}

    {_sigma3:block}
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Basis Columns

    The reference column for the Pauli representation is

    $$
    u =
    \begin{pmatrix}
    1\\
    0
    \end{pmatrix}.
    $$

    Each even basis blade acts on $u$. These four columns are the real basis of
    the column-spinor image:

    $$
    \begin{aligned}
    1u &= \begin{pmatrix}1\\0\end{pmatrix},&
    e_{12}u &= \begin{pmatrix}i\\0\end{pmatrix},\\
    e_{13}u &= \begin{pmatrix}0\\1\end{pmatrix},&
    e_{23}u &= \begin{pmatrix}0\\i\end{pmatrix}.
    \end{aligned}
    $$

    So a column $(\alpha,\beta)^T$ reconstructs the canonical even multivector

    $$
    \operatorname{Re}(\alpha) +
    \operatorname{Im}(\alpha)e_{12} +
    \operatorname{Re}(\beta)e_{13} +
    \operatorname{Im}(\beta)e_{23}.
    $$
    """)
    return


@app.cell
def _(MatrixRepr, cl3, cl3_e1, cl3_e2, cl3_e3, gm, to_spinor_column):
    _basis_scalar_col = MatrixRepr(to_spinor_column(cl3.scalar(1.0)), label=r"\operatorname{col}(1)")
    _basis_e12_col = MatrixRepr(to_spinor_column(cl3_e1 * cl3_e2), label=r"\operatorname{col}(e_{12})")
    _basis_e13_col = MatrixRepr(to_spinor_column(cl3_e1 * cl3_e3), label=r"\operatorname{col}(e_{13})")
    _basis_e23_col = MatrixRepr(to_spinor_column(cl3_e2 * cl3_e3), label=r"\operatorname{col}(e_{23})")

    gm.md(t"""
    Computed from the actual algebra:

    {_basis_scalar_col:block}

    {_basis_e12_col:block}

    {_basis_e13_col:block}

    {_basis_e23_col:block}
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## A Bloch-Sphere Rotor

    In ordinary quantum mechanics a pure spin-$\frac12$ state can be written as

    $$
    \begin{pmatrix}
    \cos(\theta/2)e^{-i\phi/2}\\
    \sin(\theta/2)e^{i\phi/2}
    \end{pmatrix}.
    $$

    In $Cl(3,0)$ the same state can be generated by an even multivector rotor

    $$
    R =
    \exp\!\left(-\frac{\phi}{2}e_{12}\right)
    \exp\!\left(-\frac{\theta}{2}e_{31}\right).
    $$

    The first expression is the QM column language. The second is the GA rotor
    language. The conversion below checks that they agree.
    """)
    return


@app.cell
def _(mo, np):
    pauli_theta_slider = mo.ui.slider(0.0, float(np.pi), value=float(np.pi / 3), step=0.01, label="theta")
    pauli_phi_slider = mo.ui.slider(0.0, float(2 * np.pi), value=float(np.pi / 4), step=0.01, label="phi")
    return pauli_phi_slider, pauli_theta_slider


@app.cell
def _(
    MatrixRepr,
    cl3,
    cl3_e1,
    cl3_e2,
    cl3_e3,
    exp,
    from_spinor_column,
    gm,
    mo,
    np,
    pauli_phi_slider,
    pauli_theta_slider,
    reverse,
    to_spinor_column,
):
    _theta = pauli_theta_slider.value
    _phi = pauli_phi_slider.value
    _e12 = (cl3_e1 * cl3_e2).eval()
    _e31 = (cl3_e3 * cl3_e1).eval()
    _pauli_rotor = (
        exp((-_phi / 2) * _e12) * exp((-_theta / 2) * _e31)
    ).name(latex=r"R")
    _pauli_column = to_spinor_column(_pauli_rotor)
    _pauli_column_expected = np.array(
        [
            [np.cos(_theta / 2) * np.exp(-1j * _phi / 2)],
            [np.sin(_theta / 2) * np.exp(1j * _phi / 2)],
        ],
        dtype=complex,
    )
    _pauli_roundtrip = from_spinor_column(cl3, _pauli_column).name(latex=r"R'")
    _pauli_roundtrip_ok = np.allclose(_pauli_roundtrip.data, _pauli_rotor.data, atol=1e-10)
    _pauli_column_ok = np.allclose(_pauli_column, _pauli_column_expected, atol=1e-10)
    _pauli_rotor_norm = _pauli_rotor * reverse(_pauli_rotor)

    mo.vstack([
    mo.hstack([pauli_theta_slider, pauli_phi_slider]),
    gm.md(t"""
    With $\\theta = {_theta:.3f}$ and $\\phi = {_phi:.3f}$:

    GA rotor:

    {_pauli_rotor.display()}

    Column from `to_spinor_column`:

    {MatrixRepr(_pauli_column, label=r"\operatorname{col}(R)"):block}

    QM expected column:

    {MatrixRepr(_pauli_column_expected, label=r"\psi_{\mathrm{QM}}"):block}

    Roundtrip through the column:

    {_pauli_roundtrip.display()}

    | Check | Result |
    |---|---|
    | Column matches QM formula | {_pauli_column_ok} |
    | `from_spinor_column(cl3, to_spinor_column(R)) == R` | {_pauli_roundtrip_ok} |
    | Rotor normalization $R\\widetilde{{R}}$ | {_pauli_rotor_norm} |
    """)
    ])
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## QM Spinor Checks: Pauli Columns

    In nonrelativistic quantum mechanics, a Pauli spinor is not just any array
    of two complex numbers viewed in isolation. It is a vector in the carrier
    space of the spin-$\frac12$ representation of $SU(2)$.

    For a rotation about the $z$ axis, the spinor transforms by

    $$
    \psi \mapsto U_z(\alpha)\psi,
    \qquad
    U_z(\alpha)=\exp\!\left(-\frac{\alpha}{2}e_{12}\right).
    $$

    The QM checks are:

    - the Hermitian norm $\psi^\dagger\psi$ is preserved;
    - a $2\pi$ rotation gives $-\psi$, while a $4\pi$ rotation gives $\psi$;
    - the expectation vector $\psi^\dagger\sigma_i\psi$ rotates as an ordinary
      three-vector.
    """)
    return


@app.cell
def _(
    MatrixRepr,
    cl3,
    cl3_e1,
    cl3_e2,
    cl3_e3,
    compact_basis,
    exp,
    gm,
    np,
    pauli_phi_slider,
    pauli_theta_slider,
    to_matrix,
    to_spinor_column,
):
    _theta = pauli_theta_slider.value
    _phi = pauli_phi_slider.value
    _alpha = 0.9
    _e12 = (cl3_e1 * cl3_e2).eval()
    _e31 = (cl3_e3 * cl3_e1).eval()
    _pauli_state_rotor = exp((-_phi / 2) * _e12) * exp((-_theta / 2) * _e31)
    _pauli_spinor = to_spinor_column(_pauli_state_rotor)
    _pauli_sigmas = compact_basis(cl3)
    _pauli_u = to_matrix(exp((-_alpha / 2) * _e12), mode="compact")
    _pauli_spinor_after = _pauli_u @ _pauli_spinor
    _pauli_norm_before = float(np.real((_pauli_spinor.conj().T @ _pauli_spinor)[0, 0]))
    _pauli_norm_after = float(np.real((_pauli_spinor_after.conj().T @ _pauli_spinor_after)[0, 0]))
    _pauli_expect = np.array(
        [[float(np.real((_pauli_spinor.conj().T @ _sigma @ _pauli_spinor)[0, 0]))] for _sigma in _pauli_sigmas]
    )
    _pauli_expect_after = np.array(
        [[float(np.real((_pauli_spinor_after.conj().T @ _sigma @ _pauli_spinor_after)[0, 0]))] for _sigma in _pauli_sigmas]
    )
    _rz = np.array(
        [
            [np.cos(_alpha), -np.sin(_alpha), 0.0],
            [np.sin(_alpha), np.cos(_alpha), 0.0],
            [0.0, 0.0, 1.0],
        ]
    )
    _pauli_expect_expected = _rz @ _pauli_expect
    _two_pi = to_matrix(exp((-2 * np.pi / 2) * _e12), mode="compact")
    _four_pi = to_matrix(exp((-4 * np.pi / 2) * _e12), mode="compact")
    _pauli_norm_ok = np.allclose(_pauli_norm_before, _pauli_norm_after, atol=1e-10)
    _pauli_two_pi_ok = np.allclose(_two_pi, -np.eye(2), atol=1e-10)
    _pauli_four_pi_ok = np.allclose(_four_pi, np.eye(2), atol=1e-10)
    _pauli_expect_ok = np.allclose(_pauli_expect_after, _pauli_expect_expected, atol=1e-10)
    _u_label = r"U_z(\alpha)"
    _expect_label = r"\langle\sigma\rangle"
    _expect_after_label = r"\langle\sigma\rangle'"
    _expect_expected_label = r"R_z(\alpha)\langle\sigma\rangle"

    gm.md(t"""
    With $\\alpha = {_alpha:.3f}$:

    {MatrixRepr(_pauli_u, label=_u_label):block}

    Spin expectation before and after applying $U_z(\\alpha)$:

    {MatrixRepr(_pauli_expect, label=_expect_label):block}

    {MatrixRepr(_pauli_expect_after, label=_expect_after_label):block}

    Expected ordinary-vector rotation:

    {MatrixRepr(_pauli_expect_expected, label=_expect_expected_label):block}

    | QM spinor check | Result |
    |---|---|
    | Hermitian norm preserved | {_pauli_norm_ok} |
    | $U_z(2\\pi) = -I$ | {_pauli_two_pi_ok} |
    | $U_z(4\\pi) = I$ | {_pauli_four_pi_ok} |
    | $\\psi^\\dagger\\sigma_i\\psi$ rotates as a vector | {_pauli_expect_ok} |
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## The Name: Column, Not Matrix

    The conversion uses matrices internally:

    $$
    \operatorname{col}(\psi)=\rho(\psi)u.
    $$

    But the returned object is the column $\operatorname{col}(\psi)$, not the
    operator matrix $\rho(\psi)$. That is why the preferred API name is
    `to_spinor_column`.
    """)
    return


@app.cell
def _(
    cl3,
    cl3_e1,
    cl3_e2,
    from_spinor_column,
    from_spinor_matrix,
    gm,
    np,
    to_spinor_column,
    to_spinor_matrix,
):
    _alias_spinor = cl3.scalar(2.0) + 0.25 * (cl3_e1 * cl3_e2).eval()
    _column_new = to_spinor_column(_alias_spinor)
    _column_old = to_spinor_matrix(_alias_spinor)
    _from_new = from_spinor_column(cl3, _column_new)
    _from_old = from_spinor_matrix(cl3, _column_old)
    _alias_columns_equal = np.allclose(_column_new, _column_old)
    _alias_inverse_equal = np.allclose(_from_new.data, _from_old.data)

    gm.md(t"""
    The old names are aliases:

    | Check | Result |
    |---|---|
    | `to_spinor_column(ψ) == to_spinor_matrix(ψ)` | {_alias_columns_equal} |
    | `from_spinor_column(...) == from_spinor_matrix(...)` | {_alias_inverse_equal} |
    """)
    return


@app.cell
def _(Algebra, b_sta):
    sta = Algebra((1, -1, -1, -1), blades=b_sta(), repr_unicode=True)
    sta_g0, sta_g1, sta_g2, sta_g3 = sta.basis_vectors(lazy=True)
    return sta, sta_g0, sta_g1, sta_g2, sta_g3


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Dirac Columns from $Cl(1,3)$

    Spacetime algebra has an 8-real-dimensional even subalgebra. The standard
    compact representation in `galaga_matrix` uses $4 \times 4$ complex Dirac
    matrices. A Dirac column has four complex entries, but the Clifford image is
    a real subspace of those complex matrices.

    The same rule still applies:

    $$
    \operatorname{col}(\psi)=\rho(\psi)u.
    $$

    For the identity even multivector, the chosen reference column is the
    familiar rest column:

    $$
    u =
    \begin{pmatrix}
    1\\0\\0\\0
    \end{pmatrix}.
    $$
    """)
    return


@app.cell
def _(MatrixRepr, compact_basis, gm, sta):
    _sta_gammas = compact_basis(sta)
    _gamma0 = MatrixRepr(_sta_gammas[0], label=r"\Gamma^0")
    _gamma1 = MatrixRepr(_sta_gammas[1], label=r"\Gamma^1")

    gm.md(t"""
    The compact $Cl(1,3)$ representation starts with:

    {_gamma0:block}

    {_gamma1:block}

    These are operator matrices. A spinor column is a vector these matrices act
    on.
    """)
    return


@app.cell
def _(mo, np):
    sta_rapidity_slider = mo.ui.slider(0.0, 1.5, value=0.6, step=0.01, label="rapidity")
    sta_rotation_slider = mo.ui.slider(0.0, float(2 * np.pi), value=0.7, step=0.01, label="spatial rotation")
    return sta_rapidity_slider, sta_rotation_slider


@app.cell
def _(
    MatrixRepr,
    compact_basis,
    exp,
    from_spinor_column,
    gm,
    mo,
    np,
    reverse,
    sta,
    sta_g0,
    sta_g1,
    sta_g2,
    sta_g3,
    sta_rapidity_slider,
    sta_rotation_slider,
    to_matrix,
    to_spinor_column,
):
    _rapidity = sta_rapidity_slider.value
    _rotation = sta_rotation_slider.value
    _boost_bivector = (sta_g0 * sta_g1).eval()
    _rotation_bivector = (sta_g2 * sta_g3).eval()
    _sta_rotor = (
        exp((_rapidity / 2) * _boost_bivector)
        * exp((-_rotation / 2) * _rotation_bivector)
    ).name(latex=r"S")
    _sta_column = to_spinor_column(_sta_rotor)
    _sta_roundtrip = from_spinor_column(sta, _sta_column).name(latex=r"S'")
    _sta_roundtrip_ok = np.allclose(_sta_roundtrip.data, _sta_rotor.data, atol=1e-10)
    _sta_matrix = to_matrix(_sta_rotor, mode="compact")
    _sta_reconstructs_column = np.allclose(_sta_matrix @ np.array([[1], [0], [0], [0]], dtype=complex), _sta_column)
    _sta_rotor_norm = _sta_rotor * reverse(_sta_rotor)
    _gamma0 = compact_basis(sta)[0]
    _hermitian_norm = float(np.real((_sta_column.conj().T @ _sta_column)[0, 0]))
    _dirac_bilinear = float(np.real((_sta_column.conj().T @ _gamma0 @ _sta_column)[0, 0]))

    mo.vstack([
    mo.hstack([sta_rapidity_slider, sta_rotation_slider]),
    gm.md(t"""
    With rapidity $\\xi = {_rapidity:.3f}$ and spatial rotation angle
    $\\varphi = {_rotation:.3f}$:

    STA even multivector:

    {_sta_rotor.display()}

    Compact operator matrix $\\rho(S)$:

    {MatrixRepr(_sta_matrix, label=r"\rho(S)"):block}

    Dirac column from `to_spinor_column`:

    {MatrixRepr(_sta_column, label=r"\operatorname{col}(S)"):block}

    Recovered even multivector:

    {_sta_roundtrip.display()}

    | Check | Result |
    |---|---|
    | $\\rho(S)u$ equals `to_spinor_column(S)` | {_sta_reconstructs_column} |
    | `from_spinor_column(sta, to_spinor_column(S)) == S` | {_sta_roundtrip_ok} |
    | Rotor normalization $S\\widetilde{{S}}$ | {_sta_rotor_norm} |
    | Ordinary column norm $\\psi^\\dagger\\psi$ | {_hermitian_norm:.6f} |
    | Dirac bilinear $\\psi^\\dagger\\Gamma^0\\psi$ | {_dirac_bilinear:.6f} |
    """)
    ])
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## QM Spinor Checks: Dirac Columns

    In relativistic quantum mechanics, a Dirac spinor is a vector in the carrier
    space of the spin representation of the Lorentz group. If $S$ is the spin
    matrix for a proper Lorentz transformation, the column transforms as

    $$
    \psi \mapsto S\psi.
    $$

    In the Dirac basis, the defining compatibility check is preservation of the
    Dirac bilinear:

    $$
    S^\dagger\Gamma^0S=\Gamma^0,
    \qquad
    \psi^\dagger\Gamma^0\psi
    =
    (S\psi)^\dagger\Gamma^0(S\psi).
    $$

    The ordinary positive-definite norm $\psi^\dagger\psi$ is not the invariant
    quantity for boosts.
    """)
    return


@app.cell
def _(
    MatrixRepr,
    compact_basis,
    exp,
    from_spinor_column,
    gm,
    np,
    sta,
    sta_g0,
    sta_g1,
    sta_g2,
    sta_g3,
    to_matrix,
    to_spinor_column,
):
    _xi = 0.65
    _varphi = 0.45
    _boost_generator = (sta_g0 * sta_g1).eval()
    _rotation_generator = (sta_g2 * sta_g3).eval()
    _spin_action = (
        exp((_xi / 2) * _boost_generator)
        * exp((-_varphi / 2) * _rotation_generator)
    ).name(latex=r"S_{\mathrm{spin}}")
    _spin_matrix = to_matrix(_spin_action, mode="compact")
    _gamma0 = compact_basis(sta)[0]
    _dirac_metric_ok = np.allclose(_spin_matrix.conj().T @ _gamma0 @ _spin_matrix, _gamma0, atol=1e-10)

    _source_even = (
        sta.scalar(0.8)
        + 0.2 * (sta_g0 * sta_g1).eval()
        - 0.15 * (sta_g0 * sta_g2).eval()
        + 0.25 * (sta_g1 * sta_g2).eval()
        + 0.3 * sta.pseudoscalar()
    ).name(latex=r"\Psi")
    _dirac_spinor = to_spinor_column(_source_even)
    _dirac_spinor_after = _spin_matrix @ _dirac_spinor
    _dirac_bilinear_before = float(np.real((_dirac_spinor.conj().T @ _gamma0 @ _dirac_spinor)[0, 0]))
    _dirac_bilinear_after = float(np.real((_dirac_spinor_after.conj().T @ _gamma0 @ _dirac_spinor_after)[0, 0]))
    _dirac_norm_before = float(np.real((_dirac_spinor.conj().T @ _dirac_spinor)[0, 0]))
    _dirac_norm_after = float(np.real((_dirac_spinor_after.conj().T @ _dirac_spinor_after)[0, 0]))
    _dirac_bilinear_ok = np.allclose(_dirac_bilinear_before, _dirac_bilinear_after, atol=1e-10)

    _dirac_roundtrip = from_spinor_column(sta, _dirac_spinor_after).name(latex=r"\Psi'")
    _expected_left_action = (_spin_action * _source_even).eval()
    _dirac_left_action_ok = np.allclose(_dirac_roundtrip.data, _expected_left_action.data, atol=1e-10)
    _spin_matrix_label = r"S_{\mathrm{spin}}"
    _spinor_label = r"\psi"
    _spinor_after_label = r"S_{\mathrm{spin}}\psi"

    gm.md(t"""
    Spin action:

    {_spin_action.display()}

    {MatrixRepr(_spin_matrix, label=_spin_matrix_label):block}

    Source and transformed Dirac columns:

    {MatrixRepr(_dirac_spinor, label=_spinor_label):block}

    {MatrixRepr(_dirac_spinor_after, label=_spinor_after_label):block}

    | Dirac spinor check | Result |
    |---|---|
    | $S^\\dagger\\Gamma^0S=\\Gamma^0$ | {_dirac_metric_ok} |
    | $\\psi^\\dagger\\Gamma^0\\psi$ preserved | {_dirac_bilinear_ok} |
    | Column action equals GA left multiplication | {_dirac_left_action_ok} |
    | Ordinary norm before | {_dirac_norm_before:.6f} |
    | Ordinary norm after boost/rotation | {_dirac_norm_after:.6f} |
    | Dirac bilinear before | {_dirac_bilinear_before:.6f} |
    | Dirac bilinear after | {_dirac_bilinear_after:.6f} |
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## General Even STA Elements

    The conversion is not limited to rotors of the form "one boost times one
    rotation". It is a linear conversion on the whole even subalgebra:

    $$
    Cl^0(1,3) =
    \operatorname{span}_{\mathbb R}
    \{1,\gamma_0\gamma_1,\gamma_0\gamma_2,\gamma_0\gamma_3,
      \gamma_1\gamma_2,\gamma_1\gamma_3,\gamma_2\gamma_3,I\}.
    $$

    A normalized Lorentz rotor is a special even multivector satisfying
    $R\widetilde R=1$. The column conversion itself does not require that
    normalization; it only requires an even multivector in a supported algebra.
    """)
    return


@app.cell
def _(
    MatrixRepr,
    exp,
    from_spinor_column,
    gm,
    np,
    reverse,
    sta,
    sta_g0,
    sta_g1,
    sta_g2,
    sta_g3,
    to_spinor_column,
):
    _general_even = (
        sta.scalar(1.25)
        + 0.20 * (sta_g0 * sta_g1).eval()
        - 0.35 * (sta_g0 * sta_g2).eval()
        + 0.45 * (sta_g0 * sta_g3).eval()
        - 0.50 * (sta_g1 * sta_g2).eval()
        + 0.60 * (sta_g1 * sta_g3).eval()
        - 0.70 * (sta_g2 * sta_g3).eval()
        + 0.80 * (sta_g0 * sta_g1 * sta_g2 * sta_g3).eval()
    ).name(latex=r"\Psi")
    _general_column = to_spinor_column(_general_even)
    _general_roundtrip = from_spinor_column(sta, _general_column).name(latex=r"\Psi'")
    _general_roundtrip_error = float(np.max(np.abs(_general_roundtrip.data - _general_even.data)))

    _multi_rotor = (
        exp(0.18 * (sta_g0 * sta_g1).eval())
        * exp(-0.11 * (sta_g0 * sta_g2).eval())
        * exp(0.24 * (sta_g2 * sta_g3).eval())
        * exp(-0.17 * (sta_g1 * sta_g3).eval())
    ).name(latex=r"M")
    _multi_column = to_spinor_column(_multi_rotor)
    _multi_roundtrip = from_spinor_column(sta, _multi_column).name(latex=r"M'")
    _multi_roundtrip_error = float(np.max(np.abs(_multi_roundtrip.data - _multi_rotor.data)))
    _multi_rotor_norm = _multi_rotor * reverse(_multi_rotor)

    gm.md(t"""
    A fully populated even multivector:

    {_general_even.display()}

    Its Dirac column:

    {MatrixRepr(_general_column, label=r"\operatorname{col}(\Psi)"):block}

    Recovered even multivector:

    {_general_roundtrip.display()}

    A product with multiple boost and rotation generators:

    {_multi_rotor.display()}

    {MatrixRepr(_multi_column, label=r"\operatorname{col}(M)"):block}

    | Check | Result |
    |---|---|
    | General even multivector roundtrip max error | {_general_roundtrip_error:.3e} |
    | Multi-factor rotor roundtrip max error | {_multi_roundtrip_error:.3e} |
    | Multi-factor rotor normalization $M\\widetilde{{M}}$ | {_multi_rotor_norm} |
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Pseudoscalar Phase Rotor

    In this section `pss` means the STA pseudoscalar

    $$
    i = \gamma_0\gamma_1\gamma_2\gamma_3.
    $$

    It is also the pseudoscalar of the relative Pauli-space basis:

    $$
    i = \sigma_1\sigma_2\sigma_3,
    \qquad
    \sigma_k=\gamma_k\gamma_0.
    $$

    The pseudoscalar squares to $-1$, so it generates a unit phase rotor:

    $$
    Q_{\mathrm{pss}}(\theta)
    =
    \exp(\theta i)
    =
    \cos\theta + i\sin\theta.
    $$

    This is not a spacetime boost or a physical rotation of a vector. It is a
    PSS/pseudoscalar phase rotor, and it still lives in the even STA subalgebra,
    so the spinor-column conversion can roundtrip it.
    """)
    return


@app.cell
def _(mo, np):
    sta_pss_phase_slider = mo.ui.slider(0.0, float(2 * np.pi), value=0.7, step=0.01, label="pseudoscalar phase")
    return (sta_pss_phase_slider,)


@app.cell
def _(
    MatrixRepr,
    exp,
    from_spinor_column,
    gm,
    mo,
    np,
    sta,
    sta_g0,
    sta_g1,
    sta_g2,
    sta_g3,
    sta_pss_phase_slider,
    to_spinor_column,
):
    _theta = sta_pss_phase_slider.value
    _pss = sta.pseudoscalar().name(latex=r"i")
    _sigma1 = (sta_g1 * sta_g0).eval().name(latex=r"\sigma_1")
    _sigma2 = (sta_g2 * sta_g0).eval().name(latex=r"\sigma_2")
    _sigma3 = (sta_g3 * sta_g0).eval().name(latex=r"\sigma_3")
    _sigma123 = (_sigma1 * _sigma2 * _sigma3).eval().name(latex=r"\sigma_1\sigma_2\sigma_3")
    _pss_phase_rotor = exp(_theta * _pss).name(latex=r"Q_{\mathrm{pss}}")
    _pss_phase_column = to_spinor_column(_pss_phase_rotor)
    _pss_expected_column = np.array(
        [[np.cos(_theta)], [0], [-1j * np.sin(_theta)], [0]],
        dtype=complex,
    )
    _pss_roundtrip = from_spinor_column(sta, _pss_phase_column).name(latex=r"Q_{\mathrm{pss}}'")
    _pss_inverse = exp((-_theta) * _pss)
    _pss_identity_check = (_pss_phase_rotor * _pss_inverse).eval()
    _pss_column_label = r"\operatorname{col}(Q_{\mathrm{pss}})"
    _pss_expected_column_label = r"(\cos\theta,0,-i\sin\theta,0)^T"
    _pss_column_ok = np.allclose(_pss_phase_column, _pss_expected_column, atol=1e-10)
    _pss_roundtrip_error = float(np.max(np.abs(_pss_roundtrip.data - _pss_phase_rotor.data)))

    mo.vstack([
        sta_pss_phase_slider,
        gm.md(t"""
    With $\\theta = {_theta:.3f}$:

    Pseudoscalar and relative-basis product:

    {_pss.display()} <br/>
    {_sigma123.display()}

    PSS phase rotor:<br/>
    {_pss_phase_rotor.display()}

    Dirac column:<br/>
    {MatrixRepr(_pss_phase_column, label=_pss_column_label):block}

    Expected column phase:<br/>
    {MatrixRepr(_pss_expected_column, label=_pss_expected_column_label):block}

    | Check | Result |
    |---|---|
    | $Q_{{\\mathrm{{pss}}}}\\exp(-\\theta i)$ | {_pss_identity_check} |
    | Column equals expected pseudoscalar-phase column | {_pss_column_ok} |
    | Roundtrip max error | {_pss_roundtrip_error:.3e} |
        """),
    ])
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Lorentzian Normalization

    The row above is intentionally different from the Pauli case.

    A Euclidean rotor in $Cl(3,0)$ maps the reference state to a unit vector
    under the ordinary Hermitian norm.

    A Lorentz rotor in $Cl(1,3)$ satisfies

    $$
    S\widetilde{S}=1,
    $$

    but a boost is not unitary under the positive-definite norm
    $\psi^\dagger\psi$. Lorentz-invariant spinor bilinears use the Dirac adjoint
    or the corresponding GA scalar bilinears.
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Quaternion Columns

    The quaternion APIs use an explicit quaternion-block representation. For
    $Cl(1,3)$ this is not the same basis as the standard Dirac compact matrix
    basis.

    The quaternion-block gamma matrices are over $M(2,\mathbb H)$:

    $$
    \gamma^0 =
    \begin{pmatrix}
    1 & 0\\
    0 & -1
    \end{pmatrix},
    \quad
    \gamma^i =
    \begin{pmatrix}
    0 & u_i\\
    u_i & 0
    \end{pmatrix},
    \qquad
    u_i \in \{i,j,k\}.
    $$

    This is why `to_spinor_quaternion` is a separate conversion, not merely a
    relabeling of the standard Dirac column.
    """)
    return


@app.cell
def _(
    QuatMatrixRepr,
    exp,
    from_spinor_quaternion,
    gm,
    np,
    sta,
    sta_g0,
    sta_g1,
    sta_g2,
    to_matrix,
    to_spinor_quaternion,
):
    _quat_rotor = (
        exp(0.25 * (sta_g0 * sta_g1).eval())
        * exp(-0.4 * (sta_g1 * sta_g2).eval())
    ).name(latex=r"Q")
    _quat_column = to_spinor_quaternion(_quat_rotor)
    _quat_roundtrip = from_spinor_quaternion(sta, _quat_column).name(latex=r"Q'")
    _quat_roundtrip_ok = np.allclose(_quat_roundtrip.data, _quat_rotor.data, atol=1e-10)
    _gamma1_quat_matrix = to_matrix(sta_g1.eval(), mode="quaternion")
    _quat_column_matrix = [[_quat_column[0]], [_quat_column[1]]]

    gm.md(t"""
    Quaternion block matrix for $\\gamma^1$:

    {QuatMatrixRepr(_gamma1_quat_matrix, label=r"\gamma^1_{\mathbb{H}}"):block}

    Quaternion spinor column:

    {QuatMatrixRepr(_quat_column_matrix, label=r"\operatorname{qcol}(Q)"):block}

    Recovered even multivector:

    {_quat_roundtrip.display()}

    Quaternion spinor roundtrip exact: {_quat_roundtrip_ok}
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## What Gets Rejected?

    The inverse is deliberately strict.

    A column conversion is allowed only when the selected reference-column map is
    injective on the even subalgebra. A supplied column must also lie in the
    image of that map. The library raises instead of returning a least-squares
    projection.
    """)
    return


@app.cell
def _(Algebra, from_spinor_column, gm, np, to_spinor_column):
    _cl31 = Algebra(3, 1)
    try:
        to_spinor_column(_cl31.scalar(1.0))
    except TypeError as _cl31_error:
        _cl31_message = str(_cl31_error)

    _cl02 = Algebra(0, 2)
    try:
        from_spinor_column(_cl02, np.array([[0], [1]], dtype=complex))
    except ValueError as _cl02_error:
        _cl02_message = str(_cl02_error)

    gm.md(t"""
    | Failure mode | Message |
    |---|---|
    | $Cl(3,1)$ even element to spinor column | `{_cl31_message}` |
    | Invalid $Cl(0,2)$ column back to even multivector | `{_cl02_message}` |
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Summary

    The conversion has two layers:

    1. **GA layer:** the spinor is an even multivector $\psi \in Cl^0(p,q)$.
    2. **QM/matrix layer:** the same information is represented by its action on
       a fixed reference column, $\rho(\psi)u$.

    The roundtrip works only when that action is injective on the even
    subalgebra. That condition is computed from the algebra, not assumed from a
    dimension table.
    """)
    return


if __name__ == "__main__":
    app.run()
